language: julia
os:
    - linux
    - osx
julia:
    - 1.0
    - 1
    - nightly
notifications:
    email: false
addons:
  apt:
    packages:
    - hdf5-tools
  homebrew:
    packages:
    - hdf5
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia -e 'using Pkg; Pkg.GitTools.clone(Pkg.Types.Context(), "https://github.com/JuliaIO/JLDArchives.jl.git", "JLDArchives")'
    - julia -e 'using Pkg; Pkg.test("JLD",coverage=true); include(joinpath("JLDArchives", "test", "runtests.jl"))'
after_success:
    - if [ $TRAVIS_JULIA_VERSION = "nightly" ]; then julia -e 'using Pkg; cd(Pkg.dir("JLD")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'; fi
